services:
  app:
    image: nextjs_image
    container_name: nextjs_movieapp
    depends_on:
      - db
    command: ["bun", "server.js"]
    env_file: ".env.production"
    networks:
      - proxy
  db:
    ports: []
  cache:
    ports: []

networks:
  proxy:
    external: true
