name: moviemania
services:
  app:
    image: nextjs_image
    container_name: nextjs_movieapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    depends_on:
      - db
    command: ["bun", "server.js"]
    env_file: ".env.development"
    networks:
      - proxy
  db:
    ports: []

networks:
  proxy:
    external: true
